### ISSUE TITLE
auth模块密钥对生成从文件读取

### ISSUE THREAD

**Issue by fanux** [fanux/fist#116]
不然每次重启后重新生成密钥对导致老的token不能用。
https://github.com/fanux/fist/blob/master/auth/jwt.go#L17

**Comment by cuisongliu** [comment]
server_k8s.go 和　server_token.go　执行了２次　Pub, Priv = CreateKeyPair()。会不会是这个原因导致？

**Comment by fanux** [comment]
执行两次肯定有问题，  执行一次也有问题，重启时重新执行了，而老的token是用重启前的私钥签的 导致老token失效，这个我这边已经有人在修复了
