### ISSUE TITLE
auth加admin账户与密码

### ISSUE THREAD

**Issue by fanux** [fanux/fist#13]
1. 安装时创建一个secrect  fist-admin 里面包含admin账户与密码
2. auth模块启动时去读取这个secrect,存在全局变量中，新建一个auth/admin.go中实现
3. 实现一个接口，判断该用户是否是管理员

```
type Admin struct {
    Name string
    Passwd string
}
type Adminer interface {
      LoadSecret()
      IsAdmin(user string)
}
```

这个功能会用于fist前端管理员登录时的校验，管理员登录后会调用创建token的接口为管理员创建token，并绑定最高权限。

**Comment by cuisongliu** [comment]
老大，这个验证是否是管理员的时候 也需要验证密码吧。
```
LoadSecret() error
IsAdmin(username string,password string) (bool,error)
```

**Comment by cuisongliu** [comment]
https://github.com/cuisongliu/fist/commit/d8a49f9b61c5c2195b659ba52c91af1f7cfa8255
功能完成。review看下。
