### ISSUE TITLE
[TODO]新建工具类

### ISSUE THREAD

**Issue by cuisongliu** [fanux/fist#21]
在fist/terminal下新建工具类
1. 创建utils.go   主要写相关k8s的工具类和其他的一些工具类
   暂定3个方法：  CreateNamespace(clientset *kubernetes.Clientset) 
                             GetK8sClient(withoutToken bool)
                            newUUID

**Comment by fanux** [comment]
想了一下，可能只有newUUID适合放进去。  其它的如果想放需要更高的抽象，不然别的地方可能用不上，单纯的封装k8s的一些接口到时可以。

**Comment by cuisongliu** [comment]
其实一开始是想直接放到fist 整个项目下加一个包专门放类似这样的结构 
fist
--auth
--terminal
--tools
  --uuid
    -- uuid.go
  --goclient
    -- goclient.go
    -- namespace.go

风格是参照client-go 的风格

**Comment by fanux** [comment]
支持，不过我们小工程，tools下就别再分级了。  这个我加cobra时统一梳理一下。
