### ISSUE TITLE
是否可以删除 PrefixSvc ， PrefixDeploy

### ISSUE THREAD

**Issue by dujiacheng** [fanux/fist#24]
func (t *Terminal) Create() error {
	t.TerminalID =  

	//create tty deployment and service
	return CreateTTYcontainer(t)
}
这里 t.TerminalID = DefaultNamespace + newUUID()
就不用到处加前缀了.  直接用 t.TerminalID  当参数即可

**Comment by dujiacheng** [comment]
https://github.com/fanux/fist/blob/5fb8916ca401b9e12d2660235fdccc42e67dce0b/terminal/terminal.go#L51

**Comment by fanux** [comment]
可以  不过觉得加DefaultNamespace有点长，直接 DefaultPrefix = "TID-" 好了，你觉得呢

**Comment by cuisongliu** [comment]
tid-uuid 这样ok.  这样后面其他接口还不用区分 前缀问题了。

**Comment by cuisongliu** [comment]
已经修复　Fix terminal #26
