### ISSUE TITLE
用户管理，创建用户

### ISSUE THREAD

**Issue by fanux** [fanux/fist#40]
1. 实现一个http接口获取用户基本信息
```
POST /user
{
   name
   passwd
 ...
}
```
2. 获取到之后为用户创建一个secret
3. 用于用户登录时校验

**Comment by cuisongliu** [comment]
```
const (
	DefaultSecretPrefix = "fist-user-"
)

type User struct {
	Name   string  `json:"name"`
	Passwd string  `json:"passwd,omitempty"`
}

type UserService interface {
	GetUser() error   // GET
	Login()               //POST
	AddUser()         //POST
	DelUser()          //DELETE
	UpdateUser()   //PUT
}
```

用户的增删改查。
登录时 需要先判断是否是admin 在进行登录验证。

**Comment by fanux** [comment]
是否有必要加用户组信息
```
type User struct {
	Name   string  `json:"name"`
	Passwd string  `json:"passwd,omitempty"`
        Groups []string `json:"groups"`
}
```
没有关系型数据库确实有点不太好维护。

**Comment by cuisongliu** [comment]
const (
	DefaultSecretPrefix = "fist-user-"
)

type User struct {
	Name   string  `json:"name"`
	Passwd string  `json:"passwd,omitempty"`
　　Groups []string `json:"groups"`
}

type UserService interface {
	GetUser() error   // GET
	AddUser()         //POST
	DelUser()          //DELETE
	UpdateUser()   //PUT
}

**Comment by fanux** [comment]
后续可能会增加一些字段或者接口，如ListUsers(), 先就这样就可以了。   我在想管理员的账户密码能不能同样走这个接口

**Comment by cuisongliu** [comment]
管理员只涉及到 GetUser这个接口吧 ？那 进入系统后可以自建管理员么？ 那这样需要把admin和用户重构一下设计。

**Comment by fanux** [comment]
看了一下，管理员的就先不动。  User的可以开始写了，还好。 然后对secret的操作可以再封装一层：
```
SetSecret(screct string, key , value string)
GetSecret(secret string)map[string]string
```
然后就是kubeclientset, 感觉我们用的有点乱，是不是搞个全局的就行了。用个单例模式

**Comment by cuisongliu** [comment]
统一了所有的kubeclientset
分离每个k8s组件
k8s_(deploy,svc,ns).go
单独放自己相关组件的工具类
重新整了了所有的日志处理
