### ISSUE TITLE
授权模块接口抽象

### ISSUE THREAD

**Issue by fanux** [fanux/fist#42]
1. 校验用户并创建token使用
2. 校验过程目前通过ldap或者k8s secret去校验用户名密码是否正确

**Comment by cuisongliu** [comment]
１．校验用户并创建token使用　这个功能放用户管理。
２．校验过程目前通过ldap或者k8s secret去校验用户名密码是否正确　　单独放一个login.go

**Comment by fanux** [comment]
Login有点偏路由层了，这个接口我觉得应该更关注认证的抽象。
```
type Authenticater interface {
       Authenticat(user, passwd string) *UserInfo //失败返回nil  成功返回用户信息
}
```
然后组装一个认证链：
```
[]Authenticater{Admin,KubeSecret,Ldap} //登录时轮着调用一遍即可，失败就继续往下轮，成功就返回
```
再给个方法往这个链上注册。  这样各种认证就能自己去实现这个接口，互不影响了

**Comment by cuisongliu** [comment]
ok.那这个就叫 authenticater.go ? 还是直接叫auth.go 。 user的设计没有问题吧。没问题我就先写user的。

**Comment by fanux** [comment]
authenticate.go
