### ISSUE TITLE
CD部署安全优化与模板优化

### ISSUE THREAD

**Issue by fanux** [fanux/fist#48]
```
http://plugins.drone.io/vallard/drone-kube/
```
vallard/drone-kube插件支持以下几个[参数](https://github.com/vallard/drone-kube/blob/master/drone-kube.go#L21)：
```
    template: deployment.yaml
    namespace: mynamespace
    server: https://10.93.234.28:6433
    ca: k8scastring
    token: xxx
```
然后可以用模板让部署镜像的tag与构建的关联，在deployment.yaml里用 {{ build.tag }}
把kubeconfig放在代码里非常不安全。
然后就可以用drone的secret放server地址和token，解决CD时部署安全性问题

**Comment by fanux** [comment]
不过此插件有很多缺陷：
1. 仅能支持deployment
2. 不能支持更新的过程，如果通过kubectl去删除deployment.yaml又会出现模板无法识别的问题

**Comment by cuisongliu** [comment]
https://github.com/vallard/drone-kube/blob/80daccfd417f170d7b48ac32cb4d4a84da0a19f7/plugin.go#L89

这里加一下删除逻辑就好了。

**Comment by fanux** [comment]
这个插件还是不太行，我感觉可以重写个，  仅支持deployment有点搓。 
我感觉插件就只需要渲染yaml文件，和渲染kubeconfig文件即可，剩下的写在command里，这样灵活一些。

**Comment by cuisongliu** [comment]
我的想法是　直接go调用kubectl。。。不用调用go-client

**Comment by cuisongliu** [comment]
https://github.com/cuisongliu/drone-kube 
模板渲染还没做

**Comment by fanux** [comment]
对，插件只做两个文件的渲染，go 可以调一下kubectl，我觉得不调都行，让用户自己写
```
  command:
       kubectl create -f xxx
```
