### ISSUE TITLE
cmd 参数

### ISSUE THREAD

**Issue by cuisongliu** [fanux/fist#64]
在cmd/auth.go 增加参数功能
目前想到就是
1. auth-type  默认password 包含选项　password/ldap
2. ldap相关参数说明
2. "/etc/fist/cert.pem", "/etc/fist/key.pem" 这俩证书地址也可以参数化

cmd/root.go 增加参数功能
1. 增加端口参数 默认8080

还有什么好的想法可以这里再想一下。

**Comment by fanux** [comment]
参数如果太多担心给用户带来负担,不过填好默认参数还行。  cmd参数用[cobra](https://github.com/spf13/cobra#create-rootcmd)

**Comment by cuisongliu** [comment]
恩恩。我写的drone-kube就是拿这个写的。。挺好用的。留参数　每个基本都有默认值。
