### ISSUE TITLE
oidc增加prefix参数

### ISSUE THREAD

**Issue by fanux** [fanux/fist#86]
部署时apiserver增加这两个参数
```
--oidc-username-prefix=“-”
--oidc-groups-prefix=“-”
```
修改部署[脚本](https://github.com/fanux/fist/blob/master/auth/deploy/install.sh#L14)
不加用户名和组名会加很长一个前缀

**Comment by cuisongliu** [comment]
https://github.com/fanux/fist/pull/132/files#diff-ace331fd741281b8ca906bc1b9588aa7R14
