### ISSUE TITLE
tty清理功能无效

### ISSUE THREAD

**Issue by fanux** [fanux/fist#88]
切一个bug fix分支，修复这个bug。

* 不需要每个terminal都创建一个协程
* 主程序启动时创建一个tty清理线程即可，每隔10min清理一下 sealyun-tty namespace下的超时 tty

**Comment by cuisongliu** [comment]
https://github.com/fanux/fist/blob/a74d09f85bf912c5a28e1506ab9e3c6ed3fcd4a5/terminal/server.go#L73
在server启动时候开启清理线程是不是好一些？

**Comment by fanux** [comment]
可以
